# Code Like It's 198x - Development Environment Makefile
# Professional retro development automation

# Configuration
DOCKER_COMPOSE = docker-compose
PROJECT_DIR = projects
EXAMPLES_DIR = examples

# System directory names (matching website slugs)
C64_DIR = commodore-64
SPECTRUM_DIR = zx-spectrum  
NES_DIR = nintendo-entertainment-system
AMIGA_DIR = commodore-amiga

# Default target
.PHONY: help
help:
	@echo "🕹️  Code Like It's 198x Development Environment"
	@echo ""
	@echo "Quick Start:"
	@echo "  make setup              Set up the development environment"
	@echo "  make new-c64 NAME=hello Create new C64 project"
	@echo "  make build-c64 PROJECT=hello Build C64 project"
	@echo ""
	@echo "Project Management:"
	@echo "  make new-c64 NAME=<name>        Create new C64 project"
	@echo "  make new-spectrum NAME=<name>   Create new ZX Spectrum project"
	@echo "  make new-nes NAME=<name>        Create new NES project"
	@echo "  make new-amiga NAME=<name>      Create new Amiga project"
	@echo ""
	@echo "Building Projects:"
	@echo "  make build-c64 PROJECT=<name>       Build C64 PRG file"
	@echo "  make build-c64-disk PROJECT=<name>  Build C64 D64 disk image"
	@echo "  make build-c64-tape PROJECT=<name>  Build C64 TAP tape image"
	@echo ""
	@echo "  make build-spectrum PROJECT=<name>  Build ZX Spectrum TAP file"
	@echo "  make build-spectrum-tzx PROJECT=<name> Build ZX Spectrum TZX file"
	@echo ""
	@echo "  make build-nes PROJECT=<name>       Build NES ROM file"
	@echo ""
	@echo "  make build-amiga PROJECT=<name>     Build Amiga executable"
	@echo "  make build-amiga-disk PROJECT=<name> Build Amiga ADF disk"
	@echo ""
	@echo "Development:"
	@echo "  make shell-dev          Open development shell"
	@echo "  make shell-c64          Open C64 development shell"
	@echo "  make clean PROJECT=<name> Clean project build files"
	@echo "  make test-all           Test all compilation tools"
	@echo ""
	@echo "Environment:"
	@echo "  make pull               Pull latest Docker images"
	@echo "  make build-images       Build Docker images locally"
	@echo "  make clean-docker       Clean Docker containers and images"

# Setup and initialization
.PHONY: setup
setup:
	@echo "🚀 Setting up Code Like It's 198x development environment..."
	@mkdir -p $(PROJECT_DIR)/{$(C64_DIR),$(SPECTRUM_DIR),$(NES_DIR),$(AMIGA_DIR)}
	@mkdir -p $(EXAMPLES_DIR)
	@$(DOCKER_COMPOSE) pull
	@$(DOCKER_COMPOSE) build
	@echo "✅ Setup complete! Try: make new-c64 NAME=hello"

# Project creation
.PHONY: new-c64
new-c64:
	@if [ -z "$(NAME)" ]; then echo "❌ Error: NAME required. Use: make new-c64 NAME=myproject"; exit 1; fi
	@echo "📁 Creating new C64 project: $(NAME)"
	@mkdir -p $(PROJECT_DIR)/$(C64_DIR)/$(NAME)
	@cp templates/c64/* $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/ 2>/dev/null || echo "📝 Creating basic project structure..."
	@echo "; $(NAME) - Commodore 64 Assembly Program" > $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "; Generated by Code Like It's 198x" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "*=\$$0801  ; BASIC start address" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo ".byte \$$0c,\$$08,\$$0a,\$$00,\$$9e,\$$20,\$$32,\$$30,\$$36,\$$31,\$$00,\$$00,\$$00" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "*=\$$080d  ; Program start" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "    lda #\$$41      ; Load 'A' character" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$0400     ; Store to screen" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "    rts             ; Return" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/$(NAME).asm
	@echo "PROJECT_NAME=$(NAME)" > $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/Makefile
	@echo "include ../../../makefiles/c64.mk" >> $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/Makefile
	@echo "✅ C64 project '$(NAME)' created in $(PROJECT_DIR)/$(C64_DIR)/$(NAME)/"

.PHONY: new-spectrum
new-spectrum:
	@if [ -z "$(NAME)" ]; then echo "❌ Error: NAME required. Use: make new-spectrum NAME=myproject"; exit 1; fi
	@echo "📁 Creating new ZX Spectrum project: $(NAME)"
	@mkdir -p $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)
	@echo "; $(NAME) - ZX Spectrum Z80 Assembly Program" > $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "; Generated by Code Like It's 198x" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "    org 32768       ; Start at 32768" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "start:" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "    ld a,2          ; Red border" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "    out (254),a     ; Set border color" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "    ret             ; Return" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/$(NAME).asm
	@echo "PROJECT_NAME=$(NAME)" > $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/Makefile
	@echo "include ../../../makefiles/spectrum.mk" >> $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/Makefile
	@echo "✅ ZX Spectrum project '$(NAME)' created in $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(NAME)/"

.PHONY: new-nes
new-nes:
	@if [ -z "$(NAME)" ]; then echo "❌ Error: NAME required. Use: make new-nes NAME=myproject"; exit 1; fi
	@echo "📁 Creating new NES project: $(NAME)"
	@mkdir -p $(PROJECT_DIR)/$(NES_DIR)/$(NAME)
	@echo "; $(NAME) - Nintendo Entertainment System 6502 Assembly" > $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "; Generated by Code Like It's 198x" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo ".segment \"HEADER\"" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .byte \"NES\", \$$1a    ; iNES header identifier" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .byte 2              ; 2 x 16KB PRG-ROM banks" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .byte 1              ; 1 x 8KB CHR-ROM bank" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .byte \$$00, \$$00      ; Mapper 0, no special flags" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .byte 0,0,0,0,0,0,0  ; Padding" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo ".segment \"CODE\"" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "reset:" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sei                  ; Disable interrupts" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    cld                  ; Clear decimal mode" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    ldx #\$$40" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    stx \$$4017           ; Disable APU frame IRQ" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    ldx #\$$ff" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    txs                  ; Set stack pointer" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    inx                  ; X = 0" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    stx \$$2000           ; Disable NMI" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    stx \$$2001           ; Disable rendering" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    stx \$$4010           ; Disable DMC IRQs" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    ; Wait for PPU to stabilize" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "vblankwait1:" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    bit \$$2002" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    bpl vblankwait1" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    ; Clear memory" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    txa                  ; A = 0" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "clearmem:" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$000,x" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$100,x" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$300,x" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$400,x" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$500,x" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$600,x" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$700,x" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    lda #\$$fe" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    sta \$$200,x          ; Move sprites off screen" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    inx" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    bne clearmem" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    ; Second wait for PPU" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "vblankwait2:" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    bit \$$2002" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    bpl vblankwait2" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    ; Main game loop" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "forever:" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    jmp forever" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "nmi:" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    rti" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo ".segment \"VECTORS\"" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .word nmi            ; NMI vector" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .word reset          ; Reset vector" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .word 0              ; IRQ vector (unused)" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo ".segment \"CHARS\"" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "    .incbin \"graphics.chr\"  ; Include CHR data" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/$(NAME).asm
	@echo "PROJECT_NAME=$(NAME)" > $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/Makefile
	@echo "include ../../../makefiles/nes.mk" >> $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/Makefile
	@echo "📺 Creating default CHR data..."
	@$(DOCKER_COMPOSE) run --rm nintendo-entertainment-system-compiler python3 /workspace/scripts/create_chr.py /workspace/projects/$(NES_DIR)/$(NAME)/graphics.chr 256
	@echo "✅ NES project '$(NAME)' created in $(PROJECT_DIR)/$(NES_DIR)/$(NAME)/"

.PHONY: new-amiga
new-amiga:
	@if [ -z "$(NAME)" ]; then echo "❌ Error: NAME required. Use: make new-amiga NAME=myproject"; exit 1; fi
	@echo "📁 Creating new Amiga project: $(NAME)"
	@mkdir -p $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)
	@echo "; $(NAME) - Commodore Amiga 68000 Assembly Program" > $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "; Generated by Code Like It's 198x" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "; Amiga OS library offsets" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "_LVOOpenLibrary     equ -552" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "_LVOCloseLibrary    equ -414" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "_LVOOutput          equ -60" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "_LVOWrite           equ -48" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "; Exec library base" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "_ExecBase           equ 4" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    section code,code" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "start:" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    movem.l d0-d7/a0-a6,-(sp)    ; Save registers" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    ; Get ExecBase" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    move.l  _ExecBase,a6" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    ; Open dos.library" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    lea     dosname(pc),a1" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    moveq   #0,d0                ; Any version" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    jsr     _LVOOpenLibrary(a6)" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    move.l  d0,dosbase" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    beq.s   .error" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    ; Get output handle" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    move.l  dosbase(pc),a6" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    jsr     _LVOOutput(a6)" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    move.l  d0,d1" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    beq.s   .cleanup" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    ; Write message" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    move.l  #message,d2" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    moveq   #msgend-message,d3" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    jsr     _LVOWrite(a6)" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo ".cleanup:" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    ; Close dos.library" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    move.l  _ExecBase,a6" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    move.l  dosbase(pc),a1" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    jsr     _LVOCloseLibrary(a6)" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo ".error:" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    movem.l (sp)+,d0-d7/a0-a6    ; Restore registers" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    moveq   #0,d0                ; Return code" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    rts" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "dosname:    dc.b    'dos.library',0" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    even" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "message:    dc.b    'Hello from $(NAME)!',10" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "msgend:" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    even" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "dosbase:    dc.l    0" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "    end" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/$(NAME).s
	@echo "PROJECT_NAME=$(NAME)" > $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/Makefile
	@echo "include ../../../makefiles/amiga.mk" >> $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/Makefile
	@echo "✅ Amiga project '$(NAME)' created in $(PROJECT_DIR)/$(AMIGA_DIR)/$(NAME)/"

# Building projects - C64
.PHONY: build-c64
build-c64:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make build-c64 PROJECT=myproject"; exit 1; fi
	@echo "🔧 Building C64 project: $(PROJECT)"
	@$(DOCKER_COMPOSE) run --rm c64-compiler /workspace/projects/$(C64_DIR)/$(PROJECT)/$(PROJECT).asm $(PROJECT) ca65 prg
	@echo "✅ Built: $(PROJECT_DIR)/$(C64_DIR)/$(PROJECT)/build/$(PROJECT).prg"

.PHONY: build-c64-disk
build-c64-disk:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make build-c64-disk PROJECT=myproject"; exit 1; fi
	@echo "💾 Building C64 disk image: $(PROJECT)"
	@$(DOCKER_COMPOSE) run --rm c64-compiler /workspace/projects/$(C64_DIR)/$(PROJECT)/$(PROJECT).asm $(PROJECT) ca65 d64
	@echo "✅ Built: $(PROJECT_DIR)/$(C64_DIR)/$(PROJECT)/build/$(PROJECT).d64"

.PHONY: build-c64-tape
build-c64-tape:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make build-c64-tape PROJECT=myproject"; exit 1; fi
	@echo "📼 Building C64 tape image: $(PROJECT)"
	@$(DOCKER_COMPOSE) run --rm c64-compiler /workspace/projects/$(C64_DIR)/$(PROJECT)/$(PROJECT).asm $(PROJECT) ca65 tap
	@echo "✅ Built: $(PROJECT_DIR)/$(C64_DIR)/$(PROJECT)/build/$(PROJECT).tap"

# Building projects - ZX Spectrum
.PHONY: build-spectrum
build-spectrum:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make build-spectrum PROJECT=myproject"; exit 1; fi
	@echo "🔧 Building ZX Spectrum project: $(PROJECT)"
	@$(DOCKER_COMPOSE) run --rm zx-spectrum-compiler /workspace/projects/$(SPECTRUM_DIR)/$(PROJECT)/$(PROJECT).asm $(PROJECT) sjasmplus tap
	@echo "✅ Built: $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(PROJECT)/build/$(PROJECT).tap"

.PHONY: build-spectrum-tzx
build-spectrum-tzx:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make build-spectrum-tzx PROJECT=myproject"; exit 1; fi
	@echo "🔧 Building ZX Spectrum TZX: $(PROJECT)"
	@$(DOCKER_COMPOSE) run --rm zx-spectrum-compiler /workspace/projects/$(SPECTRUM_DIR)/$(PROJECT)/$(PROJECT).asm $(PROJECT) sjasmplus tzx
	@echo "✅ Built: $(PROJECT_DIR)/$(SPECTRUM_DIR)/$(PROJECT)/build/$(PROJECT).tzx"

# Building projects - NES
.PHONY: build-nes
build-nes:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make build-nes PROJECT=myproject"; exit 1; fi
	@echo "🔧 Building NES project: $(PROJECT)"
	@$(DOCKER_COMPOSE) run --rm nintendo-entertainment-system-compiler /workspace/projects/$(NES_DIR)/$(PROJECT)/$(PROJECT).asm $(PROJECT) ca65 nes
	@echo "✅ Built: $(PROJECT_DIR)/$(NES_DIR)/$(PROJECT)/build/$(PROJECT).nes"

# Building projects - Amiga
.PHONY: build-amiga
build-amiga:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make build-amiga PROJECT=myproject"; exit 1; fi
	@echo "🔧 Building Amiga project: $(PROJECT)"
	@$(DOCKER_COMPOSE) run --rm commodore-amiga-compiler /workspace/projects/$(AMIGA_DIR)/$(PROJECT)/$(PROJECT).s $(PROJECT) vasm exe
	@echo "✅ Built: $(PROJECT_DIR)/$(AMIGA_DIR)/$(PROJECT)/build/$(PROJECT)"

.PHONY: build-amiga-disk
build-amiga-disk:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make build-amiga-disk PROJECT=myproject"; exit 1; fi
	@echo "💾 Building Amiga ADF disk: $(PROJECT)"
	@$(DOCKER_COMPOSE) run --rm commodore-amiga-compiler /workspace/projects/$(AMIGA_DIR)/$(PROJECT)/$(PROJECT).s $(PROJECT) vasm adf
	@echo "✅ Built: $(PROJECT_DIR)/$(AMIGA_DIR)/$(PROJECT)/build/$(PROJECT).adf"

# Development shells
.PHONY: shell-dev
shell-dev:
	@echo "🖥️  Opening development shell..."
	@$(DOCKER_COMPOSE) run --rm dev-workspace bash

.PHONY: shell-c64
shell-c64:
	@echo "🟤 Opening C64 development shell..."
	@$(DOCKER_COMPOSE) run --rm c64-compiler bash

.PHONY: shell-spectrum
shell-spectrum:
	@echo "🌈 Opening ZX Spectrum development shell..."
	@$(DOCKER_COMPOSE) run --rm zx-spectrum-compiler bash

.PHONY: shell-nes
shell-nes:
	@echo "🎮 Opening NES development shell..."
	@$(DOCKER_COMPOSE) run --rm nintendo-entertainment-system-compiler bash

.PHONY: shell-amiga
shell-amiga:
	@echo "🟦 Opening Amiga development shell..."
	@$(DOCKER_COMPOSE) run --rm commodore-amiga-compiler bash

# Testing
.PHONY: test-all
test-all:
	@echo "🧪 Testing all compilation tools..."
	@echo "Testing C64 (CA65)..."
	@$(DOCKER_COMPOSE) run --rm c64-compiler ca65 --version
	@echo "Testing C64 (ACME)..."
	@$(DOCKER_COMPOSE) run --rm c64-compiler acme --version 2>/dev/null || echo "ACME ready"
	@echo "Testing ZX Spectrum (SjASMPlus)..."
	@$(DOCKER_COMPOSE) run --rm zx-spectrum-compiler sjasmplus --version 2>/dev/null || echo "SjASMPlus ready"
	@echo "Testing NES (CA65)..."
	@$(DOCKER_COMPOSE) run --rm nintendo-entertainment-system-compiler ca65 --version
	@echo "Testing Amiga (VASM)..."
	@$(DOCKER_COMPOSE) run --rm commodore-amiga-compiler vasm68k_mot -help | head -1
	@echo "✅ All tools ready!"

# Cleanup
.PHONY: clean
clean:
	@if [ -z "$(PROJECT)" ]; then echo "❌ Error: PROJECT required. Use: make clean PROJECT=myproject"; exit 1; fi
	@echo "🧹 Cleaning project: $(PROJECT)"
	@find $(PROJECT_DIR) -name "$(PROJECT)" -type d -exec rm -rf {}/build \; 2>/dev/null || true
	@echo "✅ Cleaned build files for $(PROJECT)"

# Docker management
.PHONY: pull
pull:
	@echo "⬇️  Pulling latest Docker images..."
	@$(DOCKER_COMPOSE) pull

.PHONY: build-images
build-images:
	@echo "🔨 Building Docker images..."
	@$(DOCKER_COMPOSE) build --no-cache

.PHONY: clean-docker
clean-docker:
	@echo "🧹 Cleaning Docker containers and images..."
	@$(DOCKER_COMPOSE) down --rmi all --volumes --remove-orphans
	@docker system prune -f