import {chromium} from '@playwright/test';
import fs from 'node:fs/promises';
const [base='http://127.0.0.1:1986',output='/tmp/eight-row-checks']=process.argv.slice(2);
await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(String(e)));
const checks=[];
try {
 await page.goto(base+'/systems/sinclair-zx-spectrum/assembly/meet-assembly/unit-03/');
 const root=page.locator('.byte-lesson'),source=root.locator('textarea');
 await root.locator('.assembly-editor-colours span').first().waitFor();
 const original=await source.inputValue();
 const patterns=[24,60,126,219,255,60,102,66];
 const binary=n=>n.toString(2).padStart(8,'0');
 async function run(){await root.locator('.sandbox-run').click();await page.waitForFunction(()=>document.querySelector('.sandbox-status').textContent.startsWith('Running'))}
 async function rows(expected){await page.waitForFunction(values=>Array.from(document.querySelectorAll('[data-live-row]')).every((e,i)=>e.textContent===values[i]),expected.map(binary))}
 if(await root.locator('.readings').isVisible())throw Error('Result before execution');
 for(let row=0;row<8;row++)for(let bit=0;bit<8;bit++)if(patterns[row]&(1<<bit))await root.locator(`[data-row="${row}"][data-bit="${bit}"]`).click();
 await root.locator('.save-prediction').click();await run();await rows(patterns);
 if(!(await root.locator('.comparison').textContent()).includes('match'))throw Error('Saved eight-row prediction not compared');
 const pixels=await root.locator('.pixel-zoom').evaluate(c=>Array.from(c.getContext('2d').getImageData(0,0,8,8).data));
 for(let row=0;row<8;row++)for(let x=0;x<8;x++)if(pixels[(row*8+x)*4]!==((patterns[row]&(128>>x))?255:0))throw Error('Actual 8x8 crop mismatch');
 checks.push('64 predicted pixels match eight live RAM rows and the actual screen crop');
 await root.locator('[data-stage="1"]').click();
 await root.locator('[data-row="0"][data-bit="7"]').click();
 await root.locator('.save-prediction').click();
 const changed=[152,...patterns.slice(1)];
 if(!(await root.locator('.draft-rows').textContent()).includes('%10011000'))throw Error('Draft binary conversion missing');
 await source.fill(original.replace('%00011000','%10011000'));
 if(!(await root.locator('.observation-note').textContent()).includes('Source changed'))throw Error('Stale source not labelled');
 await run();await rows(changed);
 await root.locator('[data-stage="2"]').click();
 if(!(await source.inputValue()).includes('%10011000'))throw Error('Stage lost artwork');
 await source.fill((await source.inputValue()).replace('%00111100','%11111111').replace('($4100)','($4001)'));
 await run();await page.waitForFunction(()=>document.querySelector('.neighbour-byte').textContent.endsWith('11111111'));
 if(await root.locator('[data-live-row="1"]').textContent()==='11111111')throw Error('Wrong destination still updated row 2');
 if(!(await root.locator('.comparison').textContent()).includes('2'))throw Error('Missing row mismatch feedback');
 await root.locator('.observation').screenshot({path:output+'/wrong-address.png'});
 await source.fill((await source.inputValue()).replace('($4001)','($4100)'));
 await run();await rows([152,255,...patterns.slice(2)]);
 checks.push('custom artwork persists across experiments; misplaced row reaches $4001; repair restores row 2');
 const before=await source.inputValue();await root.locator('[data-stage="3"]').click();
 if(await source.inputValue()!==before)throw Error('Loop experiment changed source');
 await root.locator('.experiment-help summary').click();
 if(!(await root.locator('[data-explanation]').textContent()).includes('stop after eight'))throw Error('Loop boundary missing');
 const promise=page.waitForEvent('download');await root.locator('.save-source').click();const download=await promise;await download.saveAs(output+'/eight-rows.asm');
 if(download.suggestedFilename()!=='eight-rows.asm'||await fs.readFile(output+'/eight-rows.asm','utf8')!==before)throw Error('Wrong source download');
 await root.locator('.sandbox-revert').click();await run();await rows(patterns);
 checks.push('loop explanation preserves code; download saves current artwork; Revert restores all eight rows');
 await root.locator('.observation').screenshot({path:output+'/actual-character.png'});
 await page.setViewportSize({width:390,height:844});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile page overflow');
 await root.locator('[data-row="7"][data-bit="0"]').focus();await page.keyboard.press('Space');
 if(await root.locator('[data-row="7"][data-bit="0"]').getAttribute('aria-pressed')!=='true')throw Error('Keyboard grid toggle failed');
 await page.emulateMedia({forcedColors:'active'});
 if(await root.locator('[data-row="7"][data-bit="0"]').evaluate(e=>getComputedStyle(e).outlineStyle)==='none')throw Error('Forced-colours selection missing');
 checks.push('mobile no page overflow; all rows keyboard accessible; forced-colours selection visible');
 if(errors.length)throw Error(errors.join('\n'));
 await fs.writeFile(output+'/results.json',JSON.stringify(checks,null,2)+'\n');console.log(checks);
}finally{await browser.close()}
